### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by mdgriffith** [Dandandan/Easing#12]
First off, I really appreciate the library:)

In using it, I noticed a few of the functions didn't exactly match up in `ease 0 == 0` and/or in `ease 1 == 1`.  So, I went ahead and made a test suite (https://github.com/mdgriffith/elm-easing-test), which you're welcome to add to the project if you want.  Let me know and I'll make a PR.

Running the tests on pure equality, 14 easing functions failed.
I also ran the suite with the following tolerances (lower the tolerance, the better):
1% tolerance, everything passes
0.1% tolerance, 4 fail
0.01% tolerance, 12 fail
The last two fail on an incredibly low tolerance.

Here are the results that came up when I tested using pure equality:

  1 suites run, containing 60 tests
  0 suites and 46 tests passed
  1 suites and 14 tests failed
Test Suite: Elm Easing Testing Suite!: FAILED
  easeInQuad f0 == 0 : passed.
  easeInQuad f1 == 1: passed.
  easeOutQuad f0 == 0: passed.
  easeOutQuad f1 == 1: passed.
  easeInOutQuad f0 == 0: passed.
  easeInOutQuad f1 == 1: passed.
  easeInCubic f0 == 0: passed.
  easeInCubic f1 == 1: passed.
  easeOutCubic f0 == 0: passed.
  easeOutCubic f1 == 1: passed.
  easeInOutCubic f0 == 0: passed.
  easeInOutCubic f1 == 1: passed.
  easeInQuart f0 == 0: passed.
  easeInQuart f1 == 1: passed.
  easeOutQuart f0 == 0: passed.
  easeOutQuart f1 == 1: passed.
  easeInOutQuart f0 == 0: passed.
  easeInOutQuart f1 == 1: passed.
  easeInQuint f0 == 0: passed.
  easeInQuint f1 == 1: passed.
  easeOutQuint f0 == 0: passed.
  easeOutQuint f1 == 1: passed.
  easeInOutQuint f0 == 0: passed.
  easeInOutQuint f1 == 1: passed.
  easeInSine f0 == 0: passed.
  easeInSine f1 == 1: passed.
  easeOutSine f0 == 0: passed.
  easeOutSine f1 == 1: passed.
  easeInOutSine f0 == 0: passed.
  easeInOutSine f1 == 1: passed.
  easeInExpo f0 == 0: FAILED. not True
  easeInExpo f1 == 1: passed.
  easeOutExpo f0 == 0: passed.
  easeOutExpo f1 == 1: FAILED. not True
  easeInOutExpo f0 == 0: FAILED. not True
  easeInOutExpo f1 == 1: FAILED. not True
  easeInCirc f0 == 0: passed.
  easeInCirc f1 == 1: passed.
  easeOutCirc f0 == 0: passed.
  easeOutCirc f1 == 1: passed.
  easeInOutCirc f0 == 0: passed.
  easeInOutCirc f1 == 1: passed.
  easeInBack f0 == 0: passed.
  easeInBack f1 == 1: FAILED. not True
  easeOutBack f0 == 0: FAILED. not True
  easeOutBack f1 == 1: passed.
  easeInOutBack f0 == 0: passed.
  easeInOutBack f1 == 1: passed.
  easeInBounce f0 == 0: FAILED. not True
  easeInBounce f1 == 1: passed.
  easeOutBounce f0 == 0: passed.
  easeOutBounce f1 == 1: FAILED. not True
  easeInOutBounce f0 == 0: FAILED. not True
  easeInOutBounce f1 == 1: FAILED. not True
  easeInElastic f0 == 0: FAILED. not True
  easeInElastic f1 == 1: passed.
  easeOutElastic f0 == 0: passed.
  easeOutElastic f1 == 1: FAILED. not True
  easeInOutElastic f0 == 0: FAILED. not True
  easeInOutElastic f1 == 1: FAILED. not True

**Comment by Dandandan** [comment]
Wow, this is really cool! Thank you :).

I probably have some time next week to see why these fail, I think you unveiled quite a few bugs...
(Or you can have a try).

Some functions may need a guard to fix these issues, e.g. replace
```elm
 2 ^ (10 * (time - 1))
```

with

```elm
 if time == 0 then 0 else 2 ^ (10 * (time - 1))
```
