### ISSUE TITLE
0.17 and maintenance status

### ISSUE THREAD

**Issue by mgold** [Dandandan/Easing#14]
Hi Dan, are you there? I'd like to see this library updated for 0.17 because it makes my animation library more useful. If you're planning to do that, please carry on. If not, I or elm-community can fork this library, or a partial version of it.

**Comment by Dandandan** [comment]
I am still updating this library, but what changes do you need for 0.17? Generally I update my libraries when a new version of elm is released.

You could also create a PR if you want :).

**Comment by mgold** [comment]
You're welcome to wait for the official release to do the update. I've done the PR for you.

**Comment by Dandandan** [comment]
Thanks! Will do that :)

**Comment by etaque** [comment]
Hi, looks like 0.17 version hasn't been published on packages yet?

**Comment by Dandandan** [comment]
No it hasn't. The package can't be published because it begins with an upper case symbol.
Maybe it would be a good idea to fork it into elm-community  @mgold ? I would like to have access to that repository then as well.

**Comment by mgold** [comment]
Done: [elm-community/easing-functions](https://github.com/elm-community/easing-functions)

I kept just the easing functions and dropped interpolation and animation. I think this makes for a tighter, more focused package, but interpolating colors was a pretty neat trick and I'd like to find a home for it.

Elm-community is starting something called "[maintainers](https://github.com/elm-community/Manifesto/issues/16)" where each package has a [BFDL](https://en.wikipedia.org/wiki/Benevolent_dictator_for_life) who can merge PRs and stuff. Since you originated the library, would you like to maintain it? If not I can take that on.

**Comment by Dandandan** [comment]
Cool, thanks! Yes, I would like to maintain the library :).

**Comment by mgold** [comment]
Then follow the procedure and send a PR :)

If you want to add interpolations etc back in, make an issue and we can discuss (although you'll have final say).
